/* Generated by Yosys 0.63+179 (git sha1 74fef31bf, clang++ 18.1.8 -fPIC -O3) */

(* hdlname = "counter" *)
(* top =  1  *)
(* src = "vsrc/counter.v:1.1-11.10" *)
module counter(clk, rst, en, \count[0] , \count[1] );
  (* src = "vsrc/counter.v:2.9-2.12" *)
  input clk;
  wire clk;
  (* src = "vsrc/counter.v:3.9-3.12" *)
  input rst;
  wire rst;
  (* src = "vsrc/counter.v:4.9-4.11" *)
  input en;
  wire en;
  (* src = "vsrc/counter.v:5.20-5.25" *)
  output \count[0] ;
  wire \count[0] ;
  (* src = "vsrc/counter.v:5.20-5.25" *)
  output \count[1] ;
  wire \count[1] ;
  wire _00_;
  wire _01_;
  (* src = "vsrc/counter.v:5.20-5.25" *)
  wire _02_;
  (* src = "vsrc/counter.v:5.20-5.25" *)
  wire _03_;
  (* src = "vsrc/counter.v:4.9-4.11" *)
  wire _04_;
  wire _05_;
  wire _06_;
  wire _07_;
  wire _08_;
  wire _09_;
  wire _10_;
  wire _11_;
  wire _12_;
  wire _13_;
  (* src = "vsrc/counter.v:3.9-3.12" *)
  wire _14_;
  (* src = "vsrc/counter.v:9.27-9.39" *)
  wire _15_;
  (* src = "vsrc/counter.v:9.27-9.39" *)
  wire _16_;
  wire _17_;
  wire _18_;
  wire _19_;
  wire _20_;
  NOT _21_ (
    .A(_03_),
    .Y(_11_)
  );
  NOT _22_ (
    .A(_14_),
    .Y(_12_)
  );
  NAND _23_ (
    .A(_04_),
    .B(_02_),
    .Y(_13_)
  );
  NOR _24_ (
    .A(_04_),
    .B(_02_),
    .Y(_05_)
  );
  NOR _25_ (
    .A(_14_),
    .B(_05_),
    .Y(_06_)
  );
  NAND _26_ (
    .A(_13_),
    .B(_06_),
    .Y(_07_)
  );
  NOT _27_ (
    .A(_07_),
    .Y(_00_)
  );
  NOR _28_ (
    .A(_11_),
    .B(_13_),
    .Y(_08_)
  );
  NAND _29_ (
    .A(_11_),
    .B(_13_),
    .Y(_09_)
  );
  NAND _30_ (
    .A(_12_),
    .B(_09_),
    .Y(_10_)
  );
  NOR _31_ (
    .A(_08_),
    .B(_10_),
    .Y(_01_)
  );
  (* src = "vsrc/counter.v:7.3-10.6" *)
  DFF _32_ (
    .C(clk),
    .D(_18_),
    .Q(\count[0] )
  );
  (* src = "vsrc/counter.v:7.3-10.6" *)
  DFF _33_ (
    .C(clk),
    .D(_20_),
    .Q(\count[1] )
  );
  assign _03_ = \count[1] ;
  assign _04_ = en;
  assign _02_ = \count[0] ;
  assign _14_ = rst;
  assign _18_ = _00_;
  assign _20_ = _01_;
endmodule
